<a href="https://colab.research.google.com/github/Kalyan1902/DeepLearning/blob/main/wordembedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sentences =["The book on the shelf",
"A cat is sleeping on the windowsill",
"She played a beautiful melody on the piano",
"The sun sets behind the mountains",
"Learning new languages opens up new opportunities",
"Exploring different cultures enhances our understanding of the world",
"Coding is a valuable skill in today's technology-driven society",
"The smell of fresh coffee in the morning",
"Running along the beach at sunset",
"Solving complex puzzles sharpens the mind"]

In [3]:
vocabulary_size =10000
one_hot_repr = [one_hot(words,vocabulary_size)for words in sentences]
print(one_hot_repr)

[[4833, 6224, 629, 4833, 7618], [1644, 1303, 4240, 9129, 629, 4833, 3070], [9167, 3571, 1644, 4849, 9092, 629, 4833, 6188], [4833, 8761, 523, 9807, 4833, 9969], [6950, 8810, 5339, 8493, 2512, 8810, 1321], [3647, 1179, 1290, 8376, 3413, 2617, 1836, 4833, 4946], [7246, 4240, 1644, 9535, 6503, 2268, 8260, 5776, 4790, 5516], [4833, 5271, 1836, 2218, 3655, 2268, 4833, 5972], [7261, 9524, 4833, 5164, 4711, 3334], [3338, 8903, 7005, 6779, 4833, 2306]]


In [4]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np
sent_length = 10
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0    0 4833 6224  629 4833 7618]
 [   0    0    0 1644 1303 4240 9129  629 4833 3070]
 [   0    0 9167 3571 1644 4849 9092  629 4833 6188]
 [   0    0    0    0 4833 8761  523 9807 4833 9969]
 [   0    0    0 6950 8810 5339 8493 2512 8810 1321]
 [   0 3647 1179 1290 8376 3413 2617 1836 4833 4946]
 [7246 4240 1644 9535 6503 2268 8260 5776 4790 5516]
 [   0    0 4833 5271 1836 2218 3655 2268 4833 5972]
 [   0    0    0    0 7261 9524 4833 5164 4711 3334]
 [   0    0    0    0 3338 8903 7005 6779 4833 2306]]


In [11]:
dim = 10
model = Sequential()
model.add(Embedding(vocabulary_size,10,input_length=sent_length))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 10)            100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))


1/1 [==============================] - 0s 126ms/step
[[[-0.0324166  -0.03155836  0.0057889  -0.0153725  -0.00865448
    0.04617612 -0.02799542  0.03589865 -0.03570054  0.01824844]
  [-0.0324166  -0.03155836  0.0057889  -0.0153725  -0.00865448
    0.04617612 -0.02799542  0.03589865 -0.03570054  0.01824844]
  [-0.0324166  -0.03155836  0.0057889  -0.0153725  -0.00865448
    0.04617612 -0.02799542  0.03589865 -0.03570054  0.01824844]
  [-0.0324166  -0.03155836  0.0057889  -0.0153725  -0.00865448
    0.04617612 -0.02799542  0.03589865 -0.03570054  0.01824844]
  [-0.0324166  -0.03155836  0.0057889  -0.0153725  -0.00865448
    0.04617612 -0.02799542  0.03589865 -0.03570054  0.01824844]
  [ 0.0243896  -0.02493598 -0.00045158  0.00891453  0.01382974
   -0.03198675 -0.04960903 -0.02912148  0.00569062  0.03582367]
  [-0.03328202  0.02920288  0.0494051  -0.00237721  0.01740148
   -0.0121788   0.00338383  0.04616127  0.00448577  0.02712614]
  [-0.04578919 -0.03395389  0.03327229 -0.00360991  0.0187